### ISSUE TITLE
 cannot load such file -- coverage/pruner 

### ISSUE THREAD

**Issue by OrelSokolov** [seattlerb/minitest-coverage#4]
Just wanted to try this gem on my project :)

```
/home/oleg/.rvm/gems/ruby-2.3.1@sellbig/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require': cannot load such file -- coverage/pruner (LoadError)
	from /home/oleg/.rvm/gems/ruby-2.3.1@sellbig/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `block in require'
	from /home/oleg/.rvm/gems/ruby-2.3.1@sellbig/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /home/oleg/.rvm/gems/ruby-2.3.1@sellbig/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /home/oleg/.rvm/gems/ruby-2.3.1@sellbig/gems/minitest-coverage-1.0.0.b1/bin/minitest_coverage_baseline:25:in `<top (required)>'
	from /home/oleg/.rvm/gems/ruby-2.3.1@sellbig/bin/minitest_coverage_baseline:23:in `load'
	from /home/oleg/.rvm/gems/ruby-2.3.1@sellbig/bin/minitest_coverage_baseline:23:in `<main>'
	from /home/oleg/.rvm/gems/ruby-2.3.1@sellbig/bin/ruby_executable_hooks:15:in `eval'
	from /home/oleg/.rvm/gems/ruby-2.3.1@sellbig/bin/ruby_executable_hooks:15:in `<main>'

```

**Comment by zenspider** [comment]
How are you invoking this? The file is there...

**Comment by OrelSokolov** [comment]
@zenspider, I just run ` minitest_coverage_baseline`

**Comment by zenspider** [comment]
Dunno what to say. The file shipped in the gem:

```
4490 % gem i -i xxx --pre minitest-coverage 
Fetching: minitest-coverage-1.0.0.b1.gem (100%)
Successfully installed minitest-coverage-1.0.0.b1
1 gem installed
4491 % find xxx/gems/minitest-coverage-1.0.0.b1/lib -type f
xxx/gems/minitest-coverage-1.0.0.b1/lib/coverage/dumper.rb
xxx/gems/minitest-coverage-1.0.0.b1/lib/coverage/pruner.rb
xxx/gems/minitest-coverage-1.0.0.b1/lib/coverage/start.rb
xxx/gems/minitest-coverage-1.0.0.b1/lib/minitest/coverage.rb
xxx/gems/minitest-coverage-1.0.0.b1/lib/minitest/coverage_plugin.rb
```

Without some reproduction, I can't do much with this issue, as described.

**Comment by zenspider** [comment]
No response... Closing

**Comment by ghost** [comment]
@zenspider  
I got same problem here
just run minitest_coverage_baseline
and got 
```ruby
/root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `require': cannot load such file -- coverage/pruner (LoadError)
        from /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `block in require'
        from /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:258:in `load_dependency'
        from /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `require'
        from /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/minitest-coverage-1.0.0.b2/bin/minitest_coverage_baseline:41:in `<top (required)>'
        from /root/.rbenv/versions/2.4.1/bin/minitest_coverage_baseline:22:in `load'
        from /root/.rbenv/versions/2.4.1/bin/minitest_coverage_baseline:22:in `<main>'
```
